In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def prior_l0(n_states):
    prior = np.zeros((n_states, n_states))
    for i in range(n_states):
        for j in range(i):
            if i==j:
                prior[i,j]=0
                prior[j,i]=0
            else:
                prior[i,j]=2
                prior[j,i]=2
    # TODO: fill matrix such that it represents the first prior
    return prior


In [3]:
def prior_l1(n_states):
    prior = np.zeros((n_states, n_states))
    # TODO: fill matrix such that it represents the second prior
    for i in range(n_states):
        for j in range(i):
            prior[i,j]=2*np.absolute(i-j)
            prior[j,i]=2*np.absolute(i-j)
    return prior


In [4]:
def calc_proba(lattice, x, y, prior):
    
    states = []
    # TODO: fill states with probabilities for all possible n_states
    for i in range(n_states):
        prob=0
        if x<lattice.shape[0]-1: 
            prob+=prior[i,lattice[x+1,y]]
        if x>0:
            prob+=prior[i,lattice[x-1,y]]
        if y<lattice.shape[0]-1:
            prob+=prior[i,lattice[x,y+1]]
        if y>0:
            prob+=prior[i,lattice[x,y-1]]
        states.append(prob)
    return states


In [5]:
def gibbs_update(lattice, x, y, states):
    # TODO: chose new state
    new_state=np.argmin(states)
    lattice[x,y] = new_state


In [6]:
def sweep_scanlines(lattice, prior):
    # TODO: itererate over lattice and update all nodes
    for x in range(lattice.shape[0]):
        for y in range(lattice.shape[1]):
            states=calc_proba(lattice, x, y, prior)
            gibbs_update(lattice, x, y, states)
            

In [8]:
n_iter = 100
n_states = 5
n_x = 40
n_y = 40
# TODO: setup lattice to random integers between 0 and n_states with shape (n_x, n_y)
lattice=np.absolute(np.round((np.random.rand(n_x,n_y)*(n_states)-0.5)))
# TODO: call function to setup prior to be a (n_states,n_states) array
prior=prior_l1(n_states)
print(prior)

for _ in range(n_iter):
    sweep_scanlines(lattice, prior)
    
    
f = plt.figure()
ax = f.add_subplot(1, 1, 1)
ax.imshow(lattice, cmap='gray', vmax=n_states)
f.savefig("sample.png")
print(lattice[0,0])

[[ 0.  2.  4.  6.  8.]
 [ 2.  0.  2.  4.  6.]
 [ 4.  2.  0.  2.  4.]
 [ 6.  4.  2.  0.  2.]
 [ 8.  6.  4.  2.  0.]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
n_iter = 100
n_states = 5
n_x = 40
n_y = 40
# TODO: setup lattice to random integers between 0 and n_states with shape (n_x, n_y)
lattice=np.absolute(np.round((np.random.rand(n_x,n_y)*(n_states)-0.5)))
# TODO: call function to setup prior to be a (n_states,n_states) array
prior=prior_l1(n_states)
print(prior)

for _ in range(n_iter):
    sweep_scanlines(lattice, prior)
    
    
f = plt.figure()
ax = f.add_subplot(1, 1, 1)
ax.imshow(lattice, cmap='gray', vmax=n_states)
f.savefig("sample.png")
print(lattice[0,0])